### ISSUE TITLE
goToHour bug - Cannot scroll to an hour which will result the calendar to go off the screen

### ISSUE THREAD

**Issue by piotrwojtowicz** [alamkanak/Android-Week-View#106]
I have noticed today something like bug when testing my app on tablet. 

I have a fragment with calendar, by default I have 3 days visible, and in onResume I have weekview.goToHour(8) - works ok everytime. I have also three menu items changing day count to 1, 3, 7, something like:

if (id == R.id.action_schedule_7days) {
            weekview.setNumberOfVisibleDays(7);
            weekview.goToHour(8);
}

It works ok on smartphone, but on tablet it throws me:

04-12 22:24:07.944  19488-19488/com.x.y.z E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: Cannot scroll to an hour which will result the calendar to go off the screen.
            at com.alamkanak.weekview.WeekView.goToHour(WeekView.java:1386)
            at com.x.y.z.EmployeeScheduleFragment.onOptionsItemSelected(EmployeeScheduleFragment.java:337)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1894)
            at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2034)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:356)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
            at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:556)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:596)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:145)
            at android.view.View.performClick(View.java:4222)
            at android.view.View$PerformClick.run(View.java:17337)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)

PS. some clues: when I have app:hourHeight="40dp" then after goToHour(8) in onResume I see hours 8 till end and when calling again goToHour(8) error occurs. But if I change hourHeight to i.e. 60dp then after onResume I don't see last hours of day and when calling again goToHours(8) error doesn't occur. It's something like workaround but I have no guarantee that it will work always, second thing I can't allow my users to set their preferable hourHeight. 

Any clues guys? :)

**Comment by caske33** [comment]
It has to do with the fact that if you provide a hour that would make it so that 0PM would be somewhere in the middle of the screen, the library throws an exception instead of doing anything. I fixed this in one of my PR's, I think. Not sure which one anymore... 

This is the fix: https://github.com/Quivr/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L1562 (instead of throwing an exception)

**Comment by piotrwojtowicz** [comment]
I do not know if I understand correctly. You've marked me some line but I've downloaded code for Android-Week-View from alamkanak profile and I see that I have same line as yours. What I am supposed to do? :)

**Comment by caske33** [comment]
Hmm, it seems to be already merged then. Are you using the latest version of the library? (1.2.1)

**Comment by caske33** [comment]
It might be that @alamkanak needs to release a new version for you to be able to use it...

**Comment by piotrwojtowicz** [comment]
yep, using 1.2.1, I will wait then and let you know if it's fixed in new version

**Comment by fourier** [comment]
Any news on the new version with this fix? Any workaround for the current version?

**Comment by caske33** [comment]
@alamkanak Could you maybe find the time, to just release the master branch to maven?

**Comment by alamkanak** [comment]
Fixed in v1.2.3
